data_source apc_dwh:
  type: bigquery
  account_info_json_path: /usr/local/airflow/include/gcp/service_account.json
  auth_scopes:
  - https://www.googleapis.com/auth/bigquery
  - https://www.googleapis.com/auth/cloud-platform
  - https://www.googleapis.com/auth/drive
  project_id: 'data-eng-training-87b25bc6'
  dataset: apc_dwh
soda_cloud:
  host: cloud.us.soda.io
  api_key_id: "{{ env_var('SODA_KEY') }}"
  api_key_secret: "{{ env_var('SODA_SECRET') }}"
