name: Airflow-Astro CI/CD

on:
  workflow_dispatch:
    inputs:
      workspaceId:
        description: "Workspace ID"
        required: true
        type: string
      apiToken:
        description: "Astro API Token"
        required: true
        type: string
  push:
    branches:
      - main
    paths:
      - 'airflow/**'

env:
  ASTRO_API_TOKEN: ${{ inputs.apiToken || secrets.ASTRO_API_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Astro
        uses: astronomer/deploy-action@v0.4
        with:
            workspace: ${{ inputs.workspaceId || vars.WORKSPACE_ID }}
            root-folder: /airflow/
